# Generated by Django 6.0 on 2025-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, default='images/car-1.png', upload_to='media/')),
                ('blog_date', models.DateField(max_length=200)),
                ('blog_authorname', models.CharField(max_length=200)),
                ('blog_comment', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_image', models.ImageField(blank=True, default='images/car-2.png', upload_to='media/')),
                ('cat_title', models.CharField(max_length=200)),
                ('cat_rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Centalprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=200)),
                ('pro_number', models.CharField(max_length=200)),
                ('pro_desc', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_icon', models.CharField(max_length=200)),
                ('num_counter', models.CharField(max_length=200)),
                ('num_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_image', models.ImageField(blank=True, default='images/car-3.png', upload_to='media/')),
                ('review_title', models.CharField(max_length=200)),
                ('review_icon', models.CharField(max_length=200)),
                ('review_desc', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='centalfeatures',
            old_name='blog_desc',
            new_name='feat_desc',
        ),
        migrations.RenameField(
            model_name='centalfeatures',
            old_name='blog_authorname',
            new_name='feat_icon',
        ),
        migrations.RenameField(
            model_name='centalfeatures',
            old_name='blog_comment',
            new_name='feat_title',
        ),
        migrations.RemoveField(
            model_name='centalfeatures',
            name='blog_date',
        ),
        migrations.RemoveField(
            model_name='centalfeatures',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='centalfeatures',
            name='blog_title',
        ),
    ]
