# Generated by Django 6.0 on 2025-12-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0003_blog_cat_centalprocess_numbering_reviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_date', models.DateField()),
                ('drop_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
