# Generated by Django 6.0 on 2025-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0004_heroform_alter_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactsform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('emial', models.CharField(max_length=200)),
                ('your_phone', models.CharField(max_length=200)),
                ('your_projects', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
