# Generated by Django 6.0 on 2025-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_admin', '0005_contactsform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsform',
            old_name='emial',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='contactsform',
            name='msg',
            field=models.TextField(),
        ),
    ]
